### ISSUE TITLE
Network selection dialog unreadable in dark mode

### ISSUE THREAD

**Issue by vandenberghev** [beefyfinance/beefy-dashboard#14]
The BSC/HECO/AVALANCHE network selection dialog content is unreadable in dark mode; its background color seems to be wrong:

![image](https://user-images.githubusercontent.com/26387795/111619207-9448ed80-87e5-11eb-9ab5-1e4b92968191.png)

**Comment by sirbeefalot** [comment]
This is an issue for the app. Was improved here: https://github.com/beefyfinance/beefy-app/issues/250
