### ISSUE TITLE
Add missing vaults to the dashboard.

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-dashboard#8]
We've seen multiple mentions from community members that some vaults that are live on the app are missing from the dashboard.

It would be great if someone could review and check which vaults are missing from the dashboard and add them there. 

It's a perfect issue for someone looking to make their first contribution into Beefy's codebase.

**Comment by roman-monk** [comment]
should be fixed forever by fetching those pools from app 🙏  
https://github.com/beefyfinance/beefy-dashboard/pull/11
